Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -12,6 +12,8 @@ jobs:
     steps:
     - name: Checkout Repository
       uses: actions/checkout@v4
+      with:
+        submodules: recursive
 
     - name: Set up JDK 8
       uses: actions/setup-java@v4
@@ -22,28 +24,20 @@ jobs:
     - name: Install Ant
       run: sudo apt-get update && sudo apt-get install -y ant
 
-    - name: Setup Dependencies
+    - name: Setup Lib Directory
       run: |
         mkdir -p lib/android lib/appinventor lib/ant-contrib
         
-        # Mengunduh library langsung dari CDN yang stabil
-        wget -q https://raw.githubusercontent.com/mit-cml/extension-template/master/lib/android/android.jar -O lib/android/android.jar
-        wget -q https://raw.githubusercontent.com/mit-cml/extension-template/master/lib/appinventor/AnnotationProcessors.jar -O lib/appinventor/AnnotationProcessors.jar
-        wget -q https://raw.githubusercontent.com/mit-cml/extension-template/master/lib/appinventor/CommonUtils.jar -O lib/appinventor/CommonUtils.jar
-        wget -q https://raw.githubusercontent.com/mit-cml/extension-template/master/lib/appinventor/components.jar -O lib/appinventor/components.jar
-        wget -q https://raw.githubusercontent.com/mit-cml/extension-template/master/lib/appinventor/dx.jar -O lib/appinventor/dx.jar
-        wget -q https://raw.githubusercontent.com/mit-cml/extension-template/master/lib/ant-contrib/ant-contrib-1.0b3.jar -O lib/ant-contrib/ant-contrib-1.0b3.jar
-
-    - name: Check Library Integrity
-      # Jika file di bawah 100kb, kemungkinan besar itu bukan file .jar asli
-      run: |
-        find lib -name "*.jar" -exec ls -lh {} +
+        # Mengambil library dari folder deps yang sudah ada di repo Anda
+        cp deps/android/android.jar lib/android/ || echo "Android ID fail"
+        cp -r deps/appinventor/* lib/appinventor/ || echo "App Inventor lib fail"
+        cp deps/ant-contrib/ant-contrib-1.0b3.jar lib/ant-contrib/ || echo "Ant Contrib fail"
 
     - name: Build with Ant
       run: ant extensions
 
-    - name: Upload AIX
+    - name: Upload Extension Artifact
       uses: actions/upload-artifact@v4
       with:
-        name: AndroidID-v1
+        name: AndroidID-AIX-Build
         path: out/*.aix
